Add OpenLMLab/MOSS
nichtdax/awesome-totally-open-chatgpt pull request #27
Opened 2023-04-26 03:39 UTC by gptbert

2023-04-27 04:25 UTC, dinhanhx requested changes
Please add an entry in TOC section too

2023-04-27 04:25 UTC, dinhanhx commented on README.md
> +## [OpenLMLab/MOSS]([https://github.com/clue-ai/ChatYuan](https://github.com/OpenLMLab/MOSS))
This should be `[OpenLMLab/MOSS](https://github.com/OpenLMLab/MOSS)`

2023-04-27 04:25 UTC, dinhanhx commented on README.md
> +
Please add 
```
Related links:
- [English Readme](https://github.com/OpenLMLab/MOSS/blob/main/README_en.md)
```

2023-04-28 08:11 UTC, nichtdax commented
@gptbert Can you explain how is this project a derivative of LLaMa?

Quoted from [their english readme](https://github.com/OpenLMLab/MOSS/blob/main/README_en.md#:~:text=GPTQ/GPTQ%2Dfor%2DLLaMa%3A%20Quantization%20and%20inference%20backend.), 
> [GPTQ](https://github.com/IST-DASLab/gptq)/[GPTQ-for-LLaMa](https://github.com/qwopqwop200/GPTQ-for-LLaMa): Quantization and inference backend.
They only use the quantization and inference code from another project that support LLaMa

2023-05-03 02:36 UTC, merged